"""empty message

Revision ID: 60303f25d3ea
Revises: 1a50ef703141
Create Date: 2021-01-19 15:47:35.242231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60303f25d3ea'
down_revision = '1a50ef703141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
